version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 556072921029.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=556072921029.dkr.ecr.us-east-1.amazonaws.com/codebuildyourpath
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t codebuildyourpath .
      - docker tag codebuildyourpath:latest 556072921029.dkr.ecr.us-east-1.amazonaws.com/codebuildyourpath:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 556072921029.dkr.ecr.us-east-1.amazonaws.com/codebuildyourpath:latest
      - echo Writing image definitions file...
      - printf '[{"name":"hello-world","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
